### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by wishedeom** [cclp94/Damavand#1]
- [x] Payments
- [x] Improve creation of User in Client Creation
- [ ] Delete things
- [x] Edit Purchases and Permits
- [x] UI Changes
- [x] Alerts
- [x] Let Clients change their password
- [ ] Field Validation
